import "./globals.css";
import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import ConvexClientProvider from "./ConvexClientProvider";
import { ModalProvider } from "@/components/providers/modal-provider";

const sans = Exo_2({ subsets: ["cyrillic-ext", "latin"] });

export const metadata: Metadata = {
  title: "Financial Universal Bank",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/Icon_logo.svg", href: "/Icon_logo.svg" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <UserProvider>
        <body className={sans.className}>
          <ConvexClientProvider>
            <ModalProvider />
            {children}
          </ConvexClientProvider>
        </body>
      </UserProvider>
    </html>
  );
}
