import "./globals.css";
import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import ConvexClientProvider from "./ConvexClientProvider";

const sans = Exo_2({ subsets: ["cyrillic-ext", "latin"] });

export const metadata: Metadata = {
  title: "Financial Universal Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <UserProvider>
        <ConvexClientProvider>
          <body className={sans.className}>{children}</body>
        </ConvexClientProvider>
      </UserProvider>
    </html>
  );
}
