import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";

const sans = Exo_2({ subsets: ["cyrillic-ext", "latin"] });

export const metadata: Metadata = {
  title: "Financial Universal Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={sans.className}>{children}</body>
    </html>
  );
}
